/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Establishments map API is serves a list of establishments that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProviders200ResponseInner
 */
export interface GetProviders200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof GetProviders200ResponseInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetProviders200ResponseInner
     */
    name: string;
}

/**
 * Check if a given object implements the GetProviders200ResponseInner interface.
 */
export function instanceOfGetProviders200ResponseInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function GetProviders200ResponseInnerFromJSON(json: any): GetProviders200ResponseInner {
    return GetProviders200ResponseInnerFromJSONTyped(json, false);
}

export function GetProviders200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProviders200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function GetProviders200ResponseInnerToJSON(value?: GetProviders200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

